name: Deploy Evermos Project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Generate .env File
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Go Binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .

      - name: Login to Docker Hub
        run: docker login -u kimoutofkims -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t kimoutofkims/evermos .

      - name: Push Image to Docker Hub
        run: docker push kimoutofkims/evermos:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull kimoutofkims/evermos:latest
      - name: Delete Old Docker Container
        run: docker rm -f evermos-project
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name evermos-project kimoutofkims/evermos
